// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID         uuid.UUID `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	Name       string    `json:"name"`
	Price      float64   `json:"price"`
	Weight     float64   `json:"weight"`
	Calories   float64   `json:"calories"`
	Protein    float64   `json:"protein"`
	Fiber      float64   `json:"fiber"`
	Categories []string  `json:"categories"`
	Shops      []string  `json:"shops"`
}
