// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO product
(id, created_at, updated_at, name, calories, protein, fiber, price, weight, categories, shops, user_id)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2, $3, $4, $5, $6, $7, $8, $9)
    RETURNING id, name, calories, protein, fiber, price, weight, categories, shops, user_id
`

type CreateProductParams struct {
	Name       string    `json:"name"`
	Calories   float64   `json:"calories"`
	Protein    float64   `json:"protein"`
	Fiber      float64   `json:"fiber"`
	Price      float64   `json:"price"`
	Weight     float64   `json:"weight"`
	Categories []string  `json:"categories"`
	Shops      []string  `json:"shops"`
	UserID     uuid.UUID `json:"userId"`
}

type CreateProductRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Calories   float64   `json:"calories"`
	Protein    float64   `json:"protein"`
	Fiber      float64   `json:"fiber"`
	Price      float64   `json:"price"`
	Weight     float64   `json:"weight"`
	Categories []string  `json:"categories"`
	Shops      []string  `json:"shops"`
	UserID     uuid.UUID `json:"userId"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Calories,
		arg.Protein,
		arg.Fiber,
		arg.Price,
		arg.Weight,
		pq.Array(arg.Categories),
		pq.Array(arg.Shops),
		arg.UserID,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.Protein,
		&i.Fiber,
		&i.Price,
		&i.Weight,
		pq.Array(&i.Categories),
		pq.Array(&i.Shops),
		&i.UserID,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product
WHERE id=$1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, calories, protein, fiber, price, weight, categories, shops, user_id
FROM product
WHERE id=$1
`

type GetProductRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Calories   float64   `json:"calories"`
	Protein    float64   `json:"protein"`
	Fiber      float64   `json:"fiber"`
	Price      float64   `json:"price"`
	Weight     float64   `json:"weight"`
	Categories []string  `json:"categories"`
	Shops      []string  `json:"shops"`
	UserID     uuid.UUID `json:"userId"`
}

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (GetProductRow, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.Protein,
		&i.Fiber,
		&i.Price,
		&i.Weight,
		pq.Array(&i.Categories),
		pq.Array(&i.Shops),
		&i.UserID,
	)
	return i, err
}

const getProductCategories = `-- name: GetProductCategories :many
SELECT DISTINCT CAST(unnest(categories) AS TEXT) AS category
FROM product
ORDER BY category
`

func (q *Queries) GetProductCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getProductCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductShops = `-- name: GetProductShops :many
SELECT DISTINCT CAST(unnest(shops) AS TEXT) AS shop
FROM product
ORDER BY shop
`

func (q *Queries) GetProductShops(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getProductShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var shop string
		if err := rows.Scan(&shop); err != nil {
			return nil, err
		}
		items = append(items, shop)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProducts = `-- name: GetProducts :many
SELECT id, name, calories, protein, fiber, price, weight, categories, shops, user_id
FROM product
GROUP BY product.id
ORDER BY product.name
`

type GetProductsRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Calories   float64   `json:"calories"`
	Protein    float64   `json:"protein"`
	Fiber      float64   `json:"fiber"`
	Price      float64   `json:"price"`
	Weight     float64   `json:"weight"`
	Categories []string  `json:"categories"`
	Shops      []string  `json:"shops"`
	UserID     uuid.UUID `json:"userId"`
}

func (q *Queries) GetProducts(ctx context.Context) ([]GetProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsRow
	for rows.Next() {
		var i GetProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Calories,
			&i.Protein,
			&i.Fiber,
			&i.Price,
			&i.Weight,
			pq.Array(&i.Categories),
			pq.Array(&i.Shops),
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
