// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getProducts = `-- name: GetProducts :many
SELECT id, name, calories, protein, fiber, price, weight, categories, shops
FROM product
GROUP BY product.id
ORDER BY product.name
`

type GetProductsRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Calories   float64   `json:"calories"`
	Protein    float64   `json:"protein"`
	Fiber      float64   `json:"fiber"`
	Price      float64   `json:"price"`
	Weight     float64   `json:"weight"`
	Categories []string  `json:"categories"`
	Shops      []string  `json:"shops"`
}

func (q *Queries) GetProducts(ctx context.Context) ([]GetProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsRow
	for rows.Next() {
		var i GetProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Calories,
			&i.Protein,
			&i.Fiber,
			&i.Price,
			&i.Weight,
			pq.Array(&i.Categories),
			pq.Array(&i.Shops),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
